services:
  crisis-app:
    build: .
    container_name: crisis-app
    ports:
      - "4173:4173"
    restart: unless-stopped
    depends_on:
      - crisis-api

  crisis-api:
    build: ./api-json
    container_name: crisis-api
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "8080:8080"
    restart: unless-stopped
