services:
  crisis-app:
    build: .
    container_name: crisis-app
    ports:
      - "4173:4173"
    restart: unless-stopped
    depends_on:
      - crisis-api

  crisis-api:
    image: ghcr.io/typicode/json-server:latest
    container_name: crisis-api
    # on précise la commande complète (compatible quel que soit l'ENTRYPOINT)
    command: ["json-server","--host","0.0.0.0","--port","8080","/data/db.json"]
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "8080:8080"
    restart: unless-stopped
