services:
  crisis-app:
    build: .
    container_name: crisis-app
    ports:
      - "4173:4173"
    restart: unless-stopped
    depends_on:
      - api

  api:
    build: ./api
    container_name: crisis-api
    environment:
      DATABASE_URL: "postgresql://crisis:crisis@db:5432/crisis?schema=public"
      API_KEY: "${API_KEY:-changeme}"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: crisis-db
    environment:
      POSTGRES_DB: "crisis"
      POSTGRES_USER: "crisis"
      POSTGRES_PASSWORD: "crisis"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # tu peux retirer ce mapping si inutile depuis l'hôte
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crisis -d crisis"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata:
EOF
